specVersion: 0.0.1
description: ''
repository: https://github.com/tann9949/subquery-module-2
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 7513984
    mapping:
      handlers:
        # - handler: handleBlock
        #   kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        # - handler: handleExtrinsic
        #   kind: substrate/CallHandler
